POST http://localhost:3003/api/blogs 
content-Type: application/json
Authorization: Bearer 

{
    "title": "SuperBlog of John Doe",
    "author": "John Doe",
    "url": "http://www.superblog.com",
    "likes": 2
}

###